# Generated by Django 6.0.3 on 2026-03-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(unique=True)),
                ('total_registrations', models.PositiveIntegerField()),
                ('selected_registrations', models.PositiveIntegerField()),
                ('regular_cap_registrations', models.PositiveIntegerField(blank=True, null=True)),
                ('regular_cap_selected', models.PositiveIntegerField(blank=True, null=True)),
                ('masters_cap_registrations', models.PositiveIntegerField(blank=True, null=True)),
                ('masters_cap_selected', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_selection_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('regular_cap_selection_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masters_cap_selection_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('country_stats', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='CountryCapStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('india', 'India'), ('china', 'China'), ('mexico', 'Mexico'), ('philippines', 'Philippines'), ('canada', 'Canada'), ('other', 'Other')], max_length=20)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('total_applications', models.PositiveIntegerField()),
                ('approved', models.PositiveIntegerField()),
                ('denied', models.PositiveIntegerField()),
                ('pending', models.PositiveIntegerField(default=0)),
                ('priority_date_current', models.BooleanField(default=False)),
                ('priority_date_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'country cap statuses',
                'ordering': ['country', '-fiscal_year'],
                'unique_together': {('country', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='H1BApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_status', models.CharField(choices=[('certified', 'Certified'), ('certified_withdrawn', 'Certified-Withdrawn'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], max_length=30)),
                ('received_date', models.DateField()),
                ('decision_date', models.DateField()),
                ('employer_name', models.CharField(max_length=200)),
                ('employer_city', models.CharField(max_length=100)),
                ('employer_state', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=200)),
                ('soc_code', models.CharField(blank=True, max_length=20)),
                ('soc_title', models.CharField(blank=True, max_length=200)),
                ('wage_rate_of_pay_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wage_rate_of_pay_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wage_unit_of_pay', models.CharField(max_length=10)),
                ('prevailing_wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('visa_class', models.CharField(choices=[('H-1B', 'H-1B'), ('H-1B1', 'H-1B1 (Chile/Singapore)'), ('E-3', 'E-3 (Australia)')], default='H-1B', max_length=20)),
                ('full_time_position', models.BooleanField(default=True)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h1b_applications', to='companies.company')),
            ],
            options={
                'ordering': ['-fiscal_year', '-decision_date'],
                'indexes': [models.Index(fields=['fiscal_year'], name='h1b_data_h1_fiscal__d8b6bf_idx'), models.Index(fields=['employer_name'], name='h1b_data_h1_employe_604b9c_idx'), models.Index(fields=['case_status'], name='h1b_data_h1_case_st_f07d31_idx')],
            },
        ),
    ]
