# Generated by Django 6.0.3 on 2026-03-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('base_salary', models.PositiveIntegerField()),
                ('signing_bonus', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_bonus_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_grant', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_grant_years', models.PositiveIntegerField(blank=True, null=True)),
                ('other_compensation', models.TextField(blank=True)),
                ('total_compensation', models.PositiveIntegerField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, choices=[('h1b', 'H-1B'), ('h1b_transfer', 'H-1B Transfer'), ('green_card', 'Green Card Sponsorship'), ('opt', 'OPT'), ('stem_opt', 'STEM OPT'), ('no_sponsorship', 'No Sponsorship'), ('tn', 'TN Visa'), ('e3', 'E-3 Visa')], max_length=20)),
                ('visa_stage', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior (6-10 years)'), ('staff', 'Staff/Principal (10+ years)')], max_length=20)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('intern', 'Internship')], default='full_time', max_length=20)),
                ('initial_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('negotiated_increase', models.PositiveIntegerField(blank=True, null=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='companies.company')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
