# Generated by Django 5.2.12 on 2026-03-19 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_companies_c_visa_fa_9c9d59_idx_and_more'),
        ('offers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['company', 'is_verified'], name='offers_offe_company_bbbe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['submitted_by'], name='offers_offe_submitt_303be6_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['-submitted_at'], name='offers_offe_submitt_31cdc5_idx'),
        ),
    ]
