# Generated by Django 6.0.3 on 2026-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('mid', 'Mid-size (201-1000)'), ('large', 'Large (1000-5000)'), ('enterprise', 'Enterprise (5000+)')], max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('ecommerce', 'E-commerce'), ('ai', 'AI/ML'), ('other', 'Other')], max_length=20)),
                ('visa_fair_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('h1b_approval_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_salary_percentile', models.PositiveIntegerField(blank=True, null=True)),
                ('sponsorship_consistency_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_h1b_filings', models.PositiveIntegerField(default=0)),
                ('total_h1b_approvals', models.PositiveIntegerField(default=0)),
                ('total_h1b_denials', models.PositiveIntegerField(default=0)),
                ('first_filing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_filing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-visa_fair_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_experience_rating', models.PositiveSmallIntegerField()),
                ('salary_fairness_rating', models.PositiveSmallIntegerField()),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField()),
                ('visa_type', models.CharField(blank=True, max_length=20)),
                ('years_at_company', models.PositiveIntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
