# Generated by Django 5.2.12 on 2026-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to company logo image'),
        ),
    ]
