# Generated by Django 5.2.12 on 2026-03-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sponsorship_consistency_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='visa_fair_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
