# Generated by Django 5.2.12 on 2026-03-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_sponsorship_consistency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='domain_confidence',
            field=models.CharField(blank=True, choices=[('limited', 'Limited'), ('emerging', 'Emerging'), ('good', 'Good'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='domain_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_confidence',
            field=models.CharField(blank=True, choices=[('limited', 'Limited'), ('emerging', 'Emerging'), ('good', 'Good'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('retirement', 'Retirement'), ('equity', 'Equity'), ('time_off', 'Time Off'), ('family', 'Family'), ('immigration', 'Immigration'), ('learning', 'Learning'), ('other', 'Other')], default='other', max_length=20)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('community', 'Community'), ('company', 'Company'), ('manual_research', 'Manual Research')], default='community', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('confidence', models.CharField(choices=[('limited', 'Limited'), ('emerging', 'Emerging'), ('good', 'Good'), ('high', 'High')], default='emerging', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='companies.company')),
            ],
            options={
                'ordering': ['-is_verified', 'category', 'title'],
                'unique_together': {('company', 'title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('remote_policy', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField()),
                ('source', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('manual', 'Manual')], default='greenhouse', max_length=20)),
                ('source_board', models.CharField(blank=True, max_length=100)),
                ('external_job_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('visa_sponsorship_signal', models.CharField(choices=[('historically_sponsors', 'Historically Sponsors'), ('likely', 'Likely'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.company')),
            ],
            options={
                'ordering': ['-posted_at', 'title'],
                'indexes': [models.Index(fields=['source', 'source_board'], name='companies_j_source_7ce940_idx'), models.Index(fields=['is_active'], name='companies_j_is_acti_eee78a_idx')],
                'unique_together': {('company', 'source', 'external_job_id')},
            },
        ),
    ]
