# Generated by Django 5.2.12 on 2026-03-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_careers_url_company_company_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jobs_board_token',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs_last_discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs_provider',
            field=models.CharField(blank=True, choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('manual', 'Manual')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs_sync_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='source',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('manual', 'Manual')], default='greenhouse', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['posted_at'], name='companies_j_posted__d36f82_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['remote_policy'], name='companies_j_remote__417853_idx'),
        ),
    ]
