# Generated by Django 5.2.12 on 2026-03-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_jobs_board_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-visa_fair_score', 'name'], name='companies_c_visa_fa_9c9d59_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-total_h1b_filings', 'name'], name='companies_c_total_h_515bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-last_filing_year', 'name'], name='companies_c_last_fi_9ce1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'is_active'], name='companies_j_company_35192c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active', '-posted_at'], name='companies_j_is_acti_088f84_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['source', 'is_active'], name='companies_j_source_d68fcb_idx'),
        ),
    ]
