# Generated by Django 5.2.12 on 2026-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_companies_c_visa_fa_9c9d59_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
